Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/11/2017
Var
// Seção de Declarações das variáveis 
nome : vetor[1..4] de caractere
i : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 1 ate 4 faca
   escreval("Digite seu nome: ")
   leia(nome[i])
fimpara
limpatela
para i de 1 ate 4 faca
   escreval(nome[i])
fimpara

Fimalgoritmo