/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soma;

import javax.swing.JOptionPane;

/**
 *
 * @author annel
 */
public class BcdInterface extends javax.swing.JFrame {

    /**
     * Creates new form BcdInterface
     */
    public BcdInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtN1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtN2 = new javax.swing.JTextField();
        x = new javax.swing.JPanel();
        lblrefn1 = new javax.swing.JLabel();
        lblrefn2 = new javax.swing.JLabel();
        btnBin = new javax.swing.JButton();
        btnBcd = new javax.swing.JToggleButton();
        lblsomabcd = new javax.swing.JLabel();
        lblnibble = new javax.swing.JLabel();
        lbldecimal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblnibblex = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa da Anne Livia");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtN1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        txtN1.setForeground(new java.awt.Color(255, 153, 51));
        txtN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtN1KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("Número 1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 51));
        jLabel2.setText("Número 2");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtN2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        txtN2.setForeground(new java.awt.Color(255, 153, 51));

        x.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));

        lblrefn1.setBackground(new java.awt.Color(255, 255, 255));
        lblrefn1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        lblrefn1.setForeground(new java.awt.Color(255, 0, 0));

        lblrefn2.setBackground(new java.awt.Color(255, 255, 255));
        lblrefn2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        lblrefn2.setForeground(new java.awt.Color(255, 0, 0));
        lblrefn2.setToolTipText("");

        btnBin.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        btnBin.setForeground(new java.awt.Color(204, 0, 204));
        btnBin.setText(" Binário ");
        btnBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout xLayout = new javax.swing.GroupLayout(x);
        x.setLayout(xLayout);
        xLayout.setHorizontalGroup(
            xLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblrefn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblrefn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );
        xLayout.setVerticalGroup(
            xLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(lblrefn1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblrefn2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnBcd.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        btnBcd.setForeground(new java.awt.Color(204, 0, 204));
        btnBcd.setText("SOMA BCD");
        btnBcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBcdActionPerformed(evt);
            }
        });

        lblsomabcd.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        lblsomabcd.setForeground(new java.awt.Color(0, 0, 255));
        lblsomabcd.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.pink));
        lblsomabcd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblnibble.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        lblnibble.setForeground(new java.awt.Color(0, 204, 204));

        lbldecimal.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        lbldecimal.setForeground(new java.awt.Color(0, 0, 255));
        lbldecimal.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.pink));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("SOMA");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("DECIMAL");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblnibblex.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        lblnibblex.setForeground(new java.awt.Color(0, 153, 255));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 8)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("Developed by Anne Livia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(lblnibblex, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbldecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblnibble, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtN1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtN2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBcd, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblsomabcd, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsomabcd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblnibblex, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblnibble, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbldecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(btnBcd)
                .addGap(33, 33, 33)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    static void Binario(char b[], String n)
    {
          int i;
          switch(n)
          {
              case "0" : for(i = 0; i < 4; i++)
                         {
                           b[i] = '0';
                         }
                        break;
              case "1" : for(i = 0; i < 4; i++)
                         {
                           if(i == 3)
                           {
                              b[i] = '1';
                           }
                           else
                           {
                              b[i] = '0';  
                           }
                         } 
                         break;
              case "2" : for(i = 0; i < 4; i++)
                        {
                           if(i == 2)
                           {
                              b[i] = '1';
                           }
                           else
                           {
                              b[i] = '0';  
                           }
                          
                        }
                         break;
                  
              case "3" : for(i = 0; i < 4; i++)
                        {
                           if(i == 2 || i == 3)
                           {
                              b[i] = '1';
                           }
                           else
                           {
                              b[i] = '0';  
                           }
                          
                        }    
                        break;
              case "4" : for(i = 0; i < 4; i++)
                        {
                           if(i == 1)
                           {
                              b[i] = '1';
                           }
                           else
                           {
                              b[i] = '0';  
                           }
                          
                        }
                        break;
              case "5" : for(i = 0; i < 4; i++)
                        {
                           if(i == 1 || i == 3)
                           {
                              b[i] = '1';
                           }
                           else
                           {
                              b[i] = '0';  
                           }
                          
                        }
                         break;
              case "6" : for(i = 0; i < 4; i++)
                        {
                           if(i == 1 || i == 2)
                           {
                              b[i] = '1';
                           }
                           else
                           {
                              b[i] = '0';  
                           }
                          
                        }
                        break;
              case "7" : for(i = 0; i < 4; i++)
                        {
                           if(i == 1 || i == 2 || i == 3)
                           {
                              b[i] = '1';
                           }
                           else
                           {
                              b[i] = '0';  
                           }
                          
                        }
                        break;
              case "8" : for(i = 0; i < 4; i++)
                        {
                           if(i == 0)
                           {
                              b[i] = '1';
                           }
                           else
                           {
                              b[i] = '0';  
                           }
                          
                        }
                        break;
              case "9" : for(i = 0; i < 4; i++)
                        {
                           if(i == 0 || i == 3)
                           {
                              b[i] = '1';
                           }
                           else
                           {
                              b[i] = '0';  
                           }
                          
                       }
                       break;
          }
       
    }
     private void somaBCD(char bNum1[],char bNum2[], char soma[]){
       
    }
    
    private void btnBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinActionPerformed
        // TODO add your handling code here:
        
        String n1 = txtN1.getText();
        String n2 = txtN2.getText();
        if(Integer.parseInt(n1) > 9 || Integer.parseInt(n1) < 0 || Integer.parseInt(n2) > 9 || Integer.parseInt(n2) < 0)
        {
            JOptionPane.showMessageDialog(null, "Erro, você digitou algum número fora do intervalo de 0 a 9.");
            System.exit(0);
        }
        char[] bNum1 = new char[4];
        char[] bNum2 = new char[4];
        Binario(bNum1,n1);
        Binario(bNum2,n2);
        
        String binN1 = " ";
        String binN2 = " ";
        
        for(int i = 0; i < 4; i++)
        {
           binN1 += bNum1[i]; 
           binN2 += bNum2[i]; 
        } 
        
        
        lblrefn1.setText(binN1);
        lblrefn2.setText(binN2);
       
        
    }//GEN-LAST:event_btnBinActionPerformed

     void separar(String x, char y[])
    {
       for(int i = 0; i < 5; ++i)
       {
           y[i] = x.charAt(i);
       }
    }
    
    private void btnBcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBcdActionPerformed
        // TODO add your handling code here:
        char[] bNum1 = new char[5];
        char[] bNum2 = new char[5];
        separar(lblrefn1.getText(),bNum1);
        separar(lblrefn2.getText(),bNum2);
        int s = (Integer.parseInt(txtN1.getText()) + Integer.parseInt(txtN2.getText()));
        lbldecimal.setText(Integer.toString(s));
        char[] soma;
        soma = new char[5];
       
       char f = '0';
       for(int i = 4; i >= 0; i--)
       {
           if(bNum1[i] == '0' && bNum2[i] == '0' && f == '0')
           {
               soma[i] = '0';
               f = '0';
           }else if(bNum1[i] == '0' && bNum2[i] == '1' && f == '0')
           {
               soma[i] = '1';
               f = '0';
           }else if(bNum1[i] == '0' && bNum2[i] == '0' && f == '1')
           {
               soma[i] = '1';
               f = '0';   
           }else if(bNum1[i] == '0' && bNum2[i] == '1' && f == '1')
           {
               soma[i] = '0';
               f = '1';   
           }else if(bNum1[i] == '1' && bNum2[i] == '0' && f == '0')
           {
               soma[i] = '1';
               f = '0';   
           }else if(bNum1[i] == '1' && bNum2[i] == '1' && f == '0')
           {
               soma[i] = '0';
               f = '1';   
           }else if(bNum1[i] == '1' && bNum2[i] == '0' && f == '1')
           {
               soma[i] = '0';
               f = '1';   
           }else if(bNum1[i] == '1' && bNum2[i] == '1' && f == '1')
           {
               soma[i] = '1';
               f = '0';   
           }
       }
        String somaStr = " ";
        for(int i = 1; i <= 4; i++)
        {
            somaStr += soma[i];
          
        }
        lblsomabcd.setText(somaStr);
        
        if(s > 9)
        {
            lblnibblex.setText("Nibble");
            switch(s){
                case 10 : lblnibble.setText("0001 0000");
                           break;
                case 11 :  lblnibble.setText("0001 0001");
                           break;
                case 12 :  lblnibble.setText("0001 0010");
                           break;
                case 13 :  lblnibble.setText("0001 0011");
                           break;
                case 14 :  lblnibble.setText("0001 0100");
                           break;
                case 15 :  lblnibble.setText("0001 0101");
                           break;
                case 16 :  lblnibble.setText("0001 0110");
                           break;
                case 17 :  lblnibble.setText("0001 0111");
                           break;
                case 18 :  lblnibble.setText("0001 1000");
                           break;
            }
        }
        
    }//GEN-LAST:event_btnBcdActionPerformed

    private void txtN1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtN1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN1KeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BcdInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BcdInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BcdInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BcdInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BcdInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBcd;
    private javax.swing.JButton btnBin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbldecimal;
    private javax.swing.JLabel lblnibble;
    private javax.swing.JLabel lblnibblex;
    private javax.swing.JLabel lblrefn1;
    private javax.swing.JLabel lblrefn2;
    private javax.swing.JLabel lblsomabcd;
    private javax.swing.JTextField txtN1;
    private javax.swing.JTextField txtN2;
    private javax.swing.JPanel x;
    // End of variables declaration//GEN-END:variables
}
