/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author annel
 */

import javax.swing.JOptionPane;
import java.util.ArrayList;

public class Fila extends javax.swing.JFrame {

    /**
     * Creates new form Fila
     */
    
    ArrayList<String> fila = new ArrayList<>();
    
    public Fila() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFront = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelSize = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelBiggest = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelSmallest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("QUEUE");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Front:");

        jLabelFront.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabelFront.setText("none");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Size:");

        jLabelSize.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabelSize.setText("0");

        textArea1.setEditable(false);
        textArea1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setText("enqueue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setText("dequeue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Biggest:");

        jLabelBiggest.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabelBiggest.setText("none");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Smallest:");

        jLabelSmallest.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabelSmallest.setText("none");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBiggest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(jLabelSmallest))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSize)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelFront))
                            .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelFront)
                    .addComponent(jLabel4)
                    .addComponent(jLabelSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelBiggest)
                    .addComponent(jLabel5)
                    .addComponent(jLabelSmallest))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String number = JOptionPane.showInputDialog(this, "Type a number: ", "Insertion", JOptionPane.QUESTION_MESSAGE);
       
        if(number != null) {
            String exibir = "";
            if(!number.equals("")) {
                fila.add(number);
                int biggest = Integer.parseInt(fila.get(0));
                int smallest = Integer.parseInt(fila.get(0));
                for(int i = 0; i < fila.size(); i++) {
                    exibir+= "  " + fila.get(i) + "\n";
                    if(biggest < Integer.parseInt(fila.get(i))) {
                        biggest = Integer.parseInt(fila.get(i));
                    }

                    if(smallest > Integer.parseInt(fila.get(i))) {
                        smallest = Integer.parseInt(fila.get(i));
                    }
                }

                textArea1.setText(exibir);

                jLabelFront.setText(fila.get(0));
                jLabelBiggest.setText(Integer.toString(biggest));
                jLabelSize.setText(Integer.toString(fila.size()));
                jLabelSmallest.setText(Integer.toString(smallest));
            } else {
                JOptionPane.showMessageDialog(this, "Nothing was typed.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String exibir = "";
        if(!fila.isEmpty()) {
            fila.remove(0);
        
             if(fila.isEmpty()) {             
                jLabelFront.setText("none");
                jLabelSize.setText("0");
                jLabelSmallest.setText("none");
                jLabelBiggest.setText("none");
             } else { 
                int biggest = Integer.parseInt(fila.get(0));
                int smallest = Integer.parseInt(fila.get(0));
                
                for(int i = 0; i < fila.size(); i++) {
                    exibir+= "  " + fila.get(i) + "\n";
                    if(biggest < Integer.parseInt(fila.get(i))) {
                        biggest = Integer.parseInt(fila.get(i));
                    }
                
                    if(smallest > Integer.parseInt(fila.get(i))) {
                        smallest = Integer.parseInt(fila.get(i));
                    }
                }
            
                textArea1.setText(exibir);
            
                jLabelFront.setText(fila.get(0));
                jLabelSize.setText(Integer.toString(fila.size()));
                
                if(biggest != Integer.parseInt(jLabelBiggest.getText())) {
                    jLabelBiggest.setText(Integer.toString(biggest));
                }
                
                if(smallest != Integer.parseInt(jLabelSmallest.getText())) {
                    jLabelSmallest.setText(Integer.toString(smallest));
                }
             }
        } else {
            JOptionPane.showMessageDialog(this, "Queue is empty.", "Warning Message", JOptionPane.WARNING_MESSAGE);
        }
        
        textArea1.setText(exibir);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBiggest;
    private javax.swing.JLabel jLabelFront;
    private javax.swing.JLabel jLabelSize;
    private javax.swing.JLabel jLabelSmallest;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
