Algoritmo "Questão 8 Lista 1"
// Disciplina   : [ALGORITMOS]
// Professor    : YOMARA PINHEIRO PIRES
// Descrição   : Questão número 8 da lista 1
// Autor(a)    : Anne Livia da Fonseca Macedo
// Data atual  :
Var
// Seção de Declarações das variáveis 
i, num : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("Digite um número: ")
leia(num)

enquanto i <= 10 faca
   escreval(num," x ",i," = ",num*i)
   i <- i+1
fimenquanto

Fimalgoritmo